language: php
dist: xenial

services:
    - mysql

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0

env:
  - WP_VERSION=5.3 WC_VERSION=4.1
  - WP_VERSION=5.3 WC_VERSION=4.0
  - WP_VERSION=5.3 WC_VERSION=3.9

matrix:
  fast_finish: true
  include:
    - name: Coding Standards
      php: 7.3
      env: WP_TRAVISCI=phpcs
    - name: Static Code Analysis
      php: 7.3
      env: WP_TRAVISCI=phpstan
    - name: Bleeding Edge
      php: 7.4
      env: WP_VERSION=trunk WC_VERSION=latest
  allow_failures:
    - name: Bleeding Edge

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini || true

install:
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer remove --dev szepeviktor/phpstan-wordpress --no-update
      composer update --prefer-source --prefer-lowest --no-interaction --no-ansi
    else
      composer install --prefer-source --no-interaction --no-ansi
    fi
  - |
    if [[ $WP_TRAVISCI != 'phpcs' && $WP_TRAVISCI != 'phpstan' ]]; then
        bash vendor/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
        bash tests/bin/install-woocommerce.sh $WC_VERSION
    fi

script:
  - |
    if [[ $WP_TRAVISCI = 'phpcs' ]]; then
        ./vendor/bin/phpcs
    elif [[ $WP_TRAVISCI = 'phpstan' ]]; then
        ./vendor/bin/phpstan analyze
    else
      ./vendor/bin/phpunit
    fi
