language: php
dist: xenial

services:
    - mysql

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0

env:
  - WP_VERSION=5.3 WC_VERSION=4.0
  - WP_VERSION=5.3 WC_VERSION=3.9
  - WP_VERSION=5.2 WC_VERSION=4.0
  - WP_VERSION=5.2 WC_VERSION=3.9

matrix:
  fast_finish: true
  include:
    - name: Coding Standards
      php: 7.3
      env: WP_VERSION=latest WC_VERSION=latest RUN_PHPCS=1
    - name: Bleeding Edge
      php: 7.4
      env: WP_VERSION=trunk WC_VERSION=latest
  exclude:
    # WordPRess 5.2 doesn't fully support PHP 7.4.
    - php: 7.4
      env: WP_VERSION=5.2 WC_VERSION=4.0
    - php: 7.4
      env: WP_VERSION=5.2 WC_VERSION=3.9
  allow_failures:
    - name: Bleeding Edge

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - phpenv config-rm xdebug.ini || true

install:
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer update --prefer-source --prefer-lowest --no-interaction --no-ansi
    else
      composer install --prefer-source --no-interaction --no-ansi
    fi
  - |
    if [[ -z ${RUN_PHPCS} ]]; then
        bash vendor/bin/install-wp-tests.sh woocommerce_test root '' localhost $WP_VERSION
        bash tests/bin/install-woocommerce.sh $WC_VERSION
    fi

script:
  - |
    if [[ ${RUN_PHPCS} ]]; then
        ./vendor/bin/phpcs
    else
      ./vendor/bin/phpunit
    fi
